### ISSUE TITLE
[Refactor Request] Structured objects/typing

### ISSUE THREAD

**Issue by logan-markewich** [hkust-nlp/AgentBoard#3]
Amazing work here! Having tests for agents is super valuable.

Just a note to encourage contributions from other developers -- it would help to have more typing, as well as base classes for things.

Trying to wrap llama-index in this framework has been slightly confusing, since there are no types and I have to read a ton of code and debug line-by-line to see what the inputs to things are :)

**Comment by leoozy** [comment]
Thank you for your interest. We will Improve our base classees and add more comments. In the meantime, you can refer to [agent](https://github.com/hkust-nlp/AgentBoard/blob/main/assets/agent_customization.md)  and [LLM](https://github.com/hkust-nlp/AgentBoard/blob/main/assets/llm_customization.md) to warp  your LLM and add your agent.

**Comment by leoozy** [comment]
Thank you very much. We will add comments for the base classes. In the meantime, you can refer to [LLM](https://github.com/hkust-nlp/AgentBoard/blob/main/assets/llm_customization.md) and [agent ](https://github.com/hkust-nlp/AgentBoard/blob/main/assets/agent_customization.md )for adding new models/ typing.

**Comment by logan-markewich** [comment]
Thanks! 🚀
