### ISSUE TITLE
[Request] Google Gemini Pro

### ISSUE THREAD

**Issue by abdinal1** [hkust-nlp/AgentBoard#4]
Have you or can you evaluate Google Gemini Pro to put as comparison?

**Comment by chang-github-00** [comment]
Thanks for the suggestion, though we have not yet tested the performance of Google Gemini Pro on AgentBoard. We would evaluate it once we have the resources.
BTW, we also welcome everyone to contribute evaluation results of other models to our email. If you have run Google Gemini Pro on AgentBoard, you can kindly send the log file to our email ([llmagentboard@gmail.com](mailto:llmagentboard@gmail.com)).

**Comment by chang-github-00** [comment]
We've recently add evaluation on Google Gemini-flash, please check our updated arxiv.
