### ISSUE TITLE
GPT-4 model missing

### ISSUE THREAD

**Issue by yongchao98** [hkust-nlp/AgentBoard#8]
python agentboard/eval_main.py     --cfg-path eval_configs/main_results_all_tasks.yaml     --tasks scienceworld     --model gpt-4     --log_path ./results/gpt-4     --project_name evaluate-gpt-4 \

I try to test the tasks with GPT-4, but get the following errors:

  File "/home/ycchen/miniconda3/envs/Agentboard/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'OPENAI_API_TYPE'

**Comment by yc1999** [comment]
setting `OPENAI_API_TYPE="open_ai"` in file `.env` may solve this problem :)
